[phases.setup]
aptPkgs = [
  "php83Extensions.pdo_mysql",
  "php83Extensions.mysqlnd"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan optimize",
  "php artisan view:clear"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
