databases:
  - name: culture-postgres
    plan: free
    databaseName: culture
    user: culture_user

services:
  - type: web
    name: culture-benin
    env: php
    plan: free

    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan storage:link
      php artisan migrate --force
      npm install
      npm run build

    startCommand: php -S 0.0.0.0:$PORT -t public

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: LOG_CHANNEL
        value: stderr

      - key: APP_KEY
        generateValue: true

      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        fromService: culture-postgres
        property: host

      - key: DB_PORT
        fromService: culture-postgres
        property: port

      - key: DB_DATABASE
        value: culture

      - key: DB_USERNAME
        fromService: culture-postgres
        property: user

      - key: DB_PASSWORD
        fromService: culture-postgres
        property: password
