databases:
  - name: culture-postgres
    plan: free
    databaseName: culture
    user: culture_user

services:
  - type: web
    name: culture-benin
    runtime: docker
    plan: free

    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan storage:link
      php artisan migrate --force
      npm install
      npm run build

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: LOG_CHANNEL
        value: stderr

      - key: APP_KEY
        generateValue: true

      - key: DB_CONNECTION
        value: pgsql

      - key: DATABASE_URL
        fromService:
          name: culture-postgres
          type: postgresql
          property: connectionString
