databases:
  - name: culture-postgres
    plan: free
    databaseName: culture
    user: culture_user

services:
  - type: web
    name: culture-benin
    runtime: docker
    plan: free

    buildCommand: |
      echo "Docker build handled by Dockerfile"

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: LOG_CHANNEL
        value: stderr

      - key: APP_KEY
        generateValue: true

      - key: DB_CONNECTION
        value: pgsql

      - key: DATABASE_URL
        fromService:
          name: culture-postgres
          property: connectionString
